[package]
name = "autoproto-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc_macro = true

[dependencies]
anyhow = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
